### ISSUE TITLE
Doesn't work as shown in the screenshots

### ISSUE THREAD

**Issue by swingcake** [mattchrlw/dracula-for-spotify#1]
Maybe something is broken. It looks very nice though.

**Comment by mattchrlw** [comment]
Hi, so sorry for the late response - I didn't see this issue pop up! I haven't maintained this repository in a while.

I just cloned and did a fresh install of the theme and it seems to be theming everything as per the screenshot. Can you be a bit more specific with your issue? Did you `spicetify backup apply` and `spicetify apply`?

**Comment by swingcake** [comment]
I'm not using the CLI version, but the regular Spicetify instead. Running on a Windows machine, after making the change `font-family: "Roboto"` in user.css

This is [how it looks](https://imgur.com/a/Sr66ag4) after applying your theme, and this is [how it looks](https://imgur.com/a/UnCVFC9) by default.

**Comment by mattchrlw** [comment]
Hi, it seems that `spicetify`, the Windows application, uses a slightly different color format compared to `spicetify-cli`. I have updated the repo to include a new file called `color.inc` that fits the format as specified on the `spicetify` repo.

Can you please try pulling the new version of the repo/redownloading and copying the `color.inc` file into the same `SpicetifyDefault` folder, as well as removing the `color.ini` file? Please then remove and re-add the theme in the Spicetify application. (As I don't have a Windows machine, I can't test myself.) If all of that doesn't work, you can update the colors corresponding to the variables in the `color.inc` file (although I'd rather save you that hassle!)

Note: I've just noticed that `spicetify` is deprecated, so please consider using the `spicetify-cli` version in the future.

**Comment by swingcake** [comment]
> I've just noticed that spicetify is deprecated, so please consider using the spicetify-cli version in the future.  

I did not know this. I've switched to spicetify-cli now hence no need for this.
