### ISSUE TITLE
Can you add this theme to a community-driven collection?

### ISSUE THREAD

**Issue by morpheusthewhite** [mattchrlw/dracula-for-spotify#2]
I recently started on GitHub a community driven collection of themes (you can find it [here](https://github.com/morpheusthewhite/spicetify-themes)). Can you create a Pull Request to the repository (or, if you prefer, I can directly add it)?

**Comment by morpheusthewhite** [comment]
@mattchrlw

**Comment by mattchrlw** [comment]
Yep, I will send a pull request now :)

**Comment by morpheusthewhite** [comment]
Thank you
